# Global
ENABLE_PLOT = False
SCATTER_PLOT_ALPHA = 0.4
ENABLE_DEBUG_LOG = False
LIMIT_LEAF_NODE_PREVALENCE = 0.01
LIMIT_LEAF_NODE_SUBSET_SIZE = 125
NUM_FEATURES = 15

# Digits PCA
NEGATIVE_CLASS = 7
NEGATIVE_CLASS_MAPPED = -1
POSITIVE_CLASS = 9
POSITIVE_CLASS_MAPPED = 1
XP_INDEX = 400
XN_INDEX = 250
ENABLE_IMAGE_SHOW = False
FORCE_EIGEN_FLIP = True
OUT_CSV_FILE = "out/pca_overlapping_features.csv"
OUT_CSV_FD = None
OUT_STREAM = None
OUT_SKIP = True
